Fix: multiline description breaks building PyPI-compatible wheel
For reasons that I haven't traced, having a multiline `description`
field value causes `python3 setup.py sdist bdist_wheel` to build a
distribution that later fails to upload to PyPI. Running the command
`python3 -m twine check dist/*` results in the following error message
to be printed:

```
Checking dist/eprints2bags-1.9.0-py3-none-any.whl: FAILED
  `long_description` has syntax errors in markup and would not be rendered on PyPI.
    line 9: Error: Unexpected indentation.
  warning: `long_description_content_type` missing.  defaulting to `text/x-rst`.
Checking dist/eprints2bags-1.9.0.tar.gz: FAILED
  `long_description` has syntax errors in markup and would not be rendered on PyPI.
    line 9: Error: Unexpected indentation.
  warning: `long_description_content_type` missing.  defaulting to `text/x-rst`.
```

Tracing the cause of this by looking inside the dist/*.whl file
reveals that the `description` line text is broken across lines and
has other text in-between.  This apparently screws up parsing the file
by ... something (maybe the Markdown to RST converter? don't know for
sure) ... and then *that* results in the upload process to fail with
the error

```
HTTPError: 400 Client Error: The description failed to render in the
default format of reStructuredText. See
https://test.pypi.org/help/#description-content-type for more
information. for url: https://test.pypi.org/legacy/
```

Searching for clues, I couldn't find a correct solution to this
problem.  (Correct here being formatting a multiline `description`
field in some other way that wouldn't cause this error.)  I gave up
and simply shortened the `description` text.